webapp:
  extends:
    service: webapp
    file: ./etc/docker/services.yml
  environment:
    - VIRTUAL_HOST=dev.tpam.co

#worker:
#  extends:
#     service: webapp
#  command: ./docker-entrypoint.sh worker
