webapp:
  extends:
    service: webapp
    file: ./etc/docker-services.yml
  ports:
    - 8000:8000
#  environment:
#    - VIRTUAL_HOST=dev.tpam.co

#worker:
#  extends:
#     service: webapp
#  command: ./docker-entrypoint.sh worker
