webapp:
  extends:
    service: webapp
    file: ./etc/docker-services.yml
  ports:
    - 8001:8000

#worker:
#  extends:
#     service: webapp
#  command: ./docker-entrypoint.sh worker

postgres:
  image: postgres
  volumes_from:
    - db_data
  env_file:
    - ${PWD}/.env

db_data:
  image: postgres
  command: echo "DB data volume!"
  volumes:
    - /var/lib/postgresql/data