name: tpam
dependencies:
- python=3.5
- pillow
- psycopg2
- pip:
  - django
  - gunicorn
  - celery
  - redis
  - requests
  - django-import-export
  - djangorestframework
  - django-reversion
  - django-mptt
  - django-custom-field
  - django-admin-sortable
  - django-select2
  - feincms
  - django-ckeditor
  - django-custom-field==2.9
  - python-digitalocean
